
# parameters from empirical distribution
wait:
  # could be lognormal, powerlaw or truncpowerlaw 
  type: "truncpowerlaw"

  # parameter for lognormal
  mu: 0.75
  sigma: 1.49

  # parameter for powerlaw
  alpha: 1.2

  # parameters for truncpowerlaw
  parameter1: 1.1
  parameter2: 0.5

jump:
  # could be lognormal, powerlaw or truncpowerlaw 
  type: "truncpowerlaw"

  # parameter for lognormal
  mu: 7.72
  sigma: 2.38

  # parameter for powerlaw
  alpha: 1.2

  # parameters for truncpowerlaw
  parameter1: 1.1
  parameter2: 0.5

rho:
  type: "normal"
  mu: 0.64
  sigma: 0.16

gamma:
  type: "normal"
  mu: 0.18
  sigma: 0.069

# shall be within [0, 1]; change to non 0 value to perform hard interventions
P: 0.0

data_dir: "D:\\Code\\HAI-IRMA\\WP1\\npp\\data\\input"
# user:
